### ISSUE TITLE
Missing atomics support

### ISSUE THREAD

**Issue by isage** [pspdev/psptoolchain#164]
```
#include <iostream>
#include <string>
#include <atomic>

class test {
    public:
        test() {}
        ~test() {}
        void domsg(const std::string& msg);
    private:
        std::atomic<time_t> last_err_time_;
};

inline void test::domsg(const std::string& msg)
{
    auto now = time(nullptr);
    if (now - last_err_time_ < 60)
    {
        return;
    }
    last_err_time_ = now;

    std::cout << now << msg << std::endl;
}
 
int main()
{
    test t;
    t.domsg("awesome");
}

```

```
$ psp-g++ ./test.cpp -o test
/usr/local/pspdev/lib/gcc/psp/11.2.0/../../../../psp/bin/ld: /tmp/ccIkQdCm.o: in function `_ZNKSt13__atomic_baseIxEcvxEv':
(.text._ZNKSt13__atomic_baseIxEcvxEv[_ZNKSt13__atomic_baseIxEcvxEv]+0x48): undefined reference to `__atomic_load_8'
/usr/local/pspdev/lib/gcc/psp/11.2.0/../../../../psp/bin/ld: /tmp/ccIkQdCm.o: in function `_ZNSt13__atomic_baseIxEaSEx':
(.text._ZNSt13__atomic_baseIxEaSEx[_ZNSt13__atomic_baseIxEaSEx]+0x6c): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status

```

**Comment by fjtrujy** [comment]
Hello,
I think that you're doing something wrong on your side.
Here you have a dummy project with your exact example.

`https://github.com/fjtrujy/helloWorldPSP/tree/atomic`, take a look at the `atomic` branch.

I have implemented over there the `CI/CD`, and as you can see over, we can see the compilation and actually the execution using `PPSSPP`, and everything looks to work as expected. Even you can download the executable if you want 👍 

https://github.com/fjtrujy/helloWorldPSP/actions/runs/2091436034

I think that you're forgetting to link the library `-lstdc++` in your examples.

Thanks

Thanks.

**Comment by isage** [comment]
I think you forgot to push your sample or something.
This is what i get from your link:
```
// include psp headers
#include <pspkernel.h>
#include <pspdebug.h>
#include <pspdisplay.h>
#include <pspkernel.h>

#include <sys/types.h>
#include <dirent.h>
#include <stdio.h>
 
// configure PSP stuff
#define VERS    1
#define REVS    0
 
PSP_MODULE_INFO("RetroArch", 0, 1, 1);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER|THREAD_ATTR_VFPU);
 
 
// make printing easier on us
// #define printf pspDebugScreenPrintf

static int exitRequest  = 0;

static int isRunning()
{
	return !exitRequest;
}

static int exitCallback(int arg1, int arg2, void *common) 
{ 
	exitRequest = 1; 
	return 0; 
} 

static int callbackThread(SceSize args, void *argp) 
{ 
	int callbackID; 

	callbackID = sceKernelCreateCallback("Exit Callback", exitCallback, NULL); 
	sceKernelRegisterExitCallback(callbackID); 

	sceKernelSleepThreadCB(); 

	return 0; 
} 

static int setupExitCallback() 
{ 
	int threadID = 0; 

	threadID = sceKernelCreateThread("Callback Update Thread", callbackThread, 0x11, 0xFA0, THREAD_ATTR_USER, 0); 
	 
	if(threadID >= 0) 
	{ 
		sceKernelStartThread(threadID, 0, 0); 
	} 

	return threadID; 
}
 
 
int main(int argc, char** argv)
{
    // basic init
    int counter = 1;
    setupExitCallback();

	while(isRunning() && (counter % 1000) != 0) {
      printf("Working!!!\n");
      sceIoWrite(2, "foo\n", 4);
      sceIoWrite(1, "faa\n", 4);

      counter++;
   }

   //  exit
    sceKernelExitGame();
    return 0;
}
```

Also, `-lstdc++` is explicitly linked by gcc in c++ mode, but even with manual link it fails.

**Comment by isage** [comment]
it's also not stdc++ issue, but rather a missing built-in.
Which libstdc++v3 configure tells about:
```
configure:16044: checking for atomic builtins for long long
configure:16046:  /media/2TB/dev/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/./gcc/xgcc -shared-libgcc -B/media/2TB/dev/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/./gcc -nostdinc++ -L/media/2TB/dev/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/src -L/media/2TB/dev/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/src/.libs -L/media/2TB/dev/pspdev/build/psptoolchain/build/psptoolchain-allegrex/build/gcc/build-psp-stage2/psp/libstdc++-v3/libsupc++/.libs -B/usr/local/pspdev/psp/bin/ -B/usr/local/pspdev/psp/lib/ -isystem /usr/local/pspdev/psp/include -isystem /usr/local/pspdev/psp/sys-include    -c -O0 -S  conftest.cpp >&5
configure:16049: $? = 0
configure:16057: result: no
```

**Comment by fjtrujy** [comment]
When compiling `gcc` we have the next output:

```
2022-03-31T19:46:13.8403672Z #8 736.2 *** This configuration is not supported in the following subdirectories:
2022-03-31T19:46:13.8405349Z #8 736.2      target-libgomp target-libatomic target-libitm target-libsanitizer target-libvtv target-libphobos gnattools gotools target-libada target-libhsail-rt target-libstdc++-v3 target-zlib target-libbacktrace target-libgfortran target-libgo target-libffi target-libobjc target-liboffloadmic target-libssp
```

So we can clearly see how `target-libatomic` is ignored.

Maybe @davidgfnet can bring some useful info as well.

**Comment by davidgfnet** [comment]
Ok I did some extra checks :)
Platforms like x86 (32 bit) use some funny x87 instructions to do atomics (since x86 has some pretty strong guarantees about atomicity on cache-line aligned data). For MIPS I did some googling and it seems we might need to use [libatomic](https://github.com/gcc-mirror/gcc/tree/master/libatomic), which seems to be using some slow path that might rely on OS calls (mingw seems to be using some winapi mutex).
@fjtrujy I check and it seems we do not build libatomic while building gcc, but I dont think we disable it explicitely. Perhaps we need to enable (like disabled by default)?

**Comment by isage** [comment]
It is disabled by default, but it looks like it lacks support for mips (configure throws UNSUPPORTED when enabled)

**Comment by isage** [comment]
I think we can use posix (pthreads) fallback in libatomic, though.

**Comment by davidgfnet** [comment]
Yup! @fjtrujy will add the pthread path and we can use that indeed! It will be... Slow but usable :)

**Comment by isage** [comment]
```
diff --git a/libatomic/configure.tgt b/libatomic/configure.tgt
index 670b0d72c..f360b39ec 100644
--- a/libatomic/configure.tgt
+++ b/libatomic/configure.tgt
@@ -148,7 +148,7 @@ case "${target}" in
        tmake_file="t-aix"
        ;;
 
-  *-*-linux* | *-*-gnu* | *-*-k*bsd*-gnu \
+  mipsallegrex* | *-*-linux* | *-*-gnu* | *-*-k*bsd*-gnu \
   | *-*-netbsd* | *-*-freebsd* | *-*-openbsd* | *-*-dragonfly* \
   | *-*-solaris2* | *-*-sysv4* | *-*-irix6* | *-*-osf* | *-*-hpux11* \
   | *-*-darwin* | *-*-aix* | *-*-cygwin*)
```
seems to do the trick

**Comment by fjtrujy** [comment]
Nice!! Probably is better to compare by the OS, in our case psp, I will try it and create PR

**Comment by fjtrujy** [comment]
> ```
> diff --git a/libatomic/configure.tgt b/libatomic/configure.tgt
> index 670b0d72c..f360b39ec 100644
> --- a/libatomic/configure.tgt
> +++ b/libatomic/configure.tgt
> @@ -148,7 +148,7 @@ case "${target}" in
>         tmake_file="t-aix"
>         ;;
>  
> -  *-*-linux* | *-*-gnu* | *-*-k*bsd*-gnu \
> +  mipsallegrex* | *-*-linux* | *-*-gnu* | *-*-k*bsd*-gnu \
>    | *-*-netbsd* | *-*-freebsd* | *-*-openbsd* | *-*-dragonfly* \
>    | *-*-solaris2* | *-*-sysv4* | *-*-irix6* | *-*-osf* | *-*-hpux11* \
>    | *-*-darwin* | *-*-aix* | *-*-cygwin*)
> ```
> 
> seems to do the trick (program needs to be linked with libatomic then. i guess it needs to be added to gcc built-in libs list)

It wasn't as easy as you said at the end.... 
I want to keep the separation between `psptoolchain` and the `pspsdk`, however `libatomic` makes some tests to assure that it can generate binaries, however at that point, we still don't have anything related to `pspsdk` libraries, so the best we can do for now is just to skip these tests...

You can take a look the proposed changes here:

https://github.com/fjtrujy/gcc/commits/allegrex-v11.2.0-atomic

Thanks

**Comment by fjtrujy** [comment]
And as you can see here, I made it to work:

https://github.com/fjtrujy/helloWorldPSP/actions/runs/2094682360

**Comment by isage** [comment]
> It wasn't as easy as you said at the end.... I want to keep the separation between `psptoolchain` and the `pspsdk`, however `libatomic` makes some tests to assure that it can generate binaries, however at that point, we still don't have anything related to `pspsdk` libraries, so the best we can do for now is just to skip these tests...

what if you disable libatomic for bootstrap build and enable it only for final gcc build?

**Comment by fjtrujy** [comment]
> > It wasn't as easy as you said at the end.... I want to keep the separation between `psptoolchain` and the `pspsdk`, however `libatomic` makes some tests to assure that it can generate binaries, however at that point, we still don't have anything related to `pspsdk` libraries, so the best we can do for now is just to skip these tests...
> 
> what if you disable libatomic for bootstrap build and enable it only for final gcc build?

You still would need to compile the library after compiling `pspsdk` libraries, and I'm trying to keep a single flow without "circle" dependencies, this is the best for having a good CI/CD system and different docker layer per repository.

Just for adding some useful information, the layers are (the most important ones), every layer contains the previous one:
0. alpine
1. psptoolchain
2. pspsdk
3. psp-packages
4. pspdev

So the critical part here is to compile `psptoolchain`, in this case `libatomic` without knowing anything of `pspsdk` at all.

Thanks

**Comment by fjtrujy** [comment]
@isage I'm going to close this issue, feel free to re-open it if it is not working properly.
